name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
